### ISSUE TITLE
current release on pypi is broken

### ISSUE THREAD

**Issue by simahawk** [collective/collective.js.jwplayer#1]
current release misses README.rst so that installation is broken.

see https://pypi.python.org/packages/source/c/collective.js.jwplayer/collective.js.jwplayer-1.1.zip

**Comment by toutpt** [comment]
You right, I forgot to update the manifest and test the release. Sorry for that. Could you update it ? I can give you rights on pypi and plone (just give me your username on both)

**Comment by simahawk** [comment]
simahawk on both, tnx

**Comment by toutpt** [comment]
done, you can go ahead now !

**Comment by simahawk** [comment]
what about moving package version to js version (5.10 ATM, 6 available)?

**Comment by toutpt** [comment]
I do that way most of the time, I duno why not here.

**Comment by simahawk** [comment]
upgraded, changed version, fixed release.

**Comment by toutpt** [comment]
thanks @simahawk
